modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="civil_to_the_max"
version="1.0.0"
displayName="Civil to the Max"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="电磁相互作用力, 引力, 弱相互作用力, MCreator"

[[dependencies.civil_to_the_max]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




